# Build WEST.Native project from dev branch in GitHub
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

variables:
  versionprefix: 0.1.0

jobs:
  - job: 'BuildAndPublishNative'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
          rid: 'linux-x64'
        mac:
          imageName: 'macos-latest'
          rid: 'osx-x64'
        windows:
          rid: 'windows-x64'
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)

    variables:
      buildConfiguration: 'Release'

    steps:
    #Install dependencies
    - task: CmdLine@2
      displayName: 'Install linux dependencies'
      condition: eq(variables.rid, 'linux-x64')
      inputs:
        script: 'sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev'
    - task: NuGetCommand@2
      displayName: 'NuGet package restore for Windows native packages'
      condition: eq(variables.rid, 'windows-x64')
      inputs:
        command: 'restore'
        restoreSolution: 'WebWindow.Native.sln'
        feedsToUse: 'select'
        
    #Build
    - task: VSBuild@1
      displayName: 'Build Windows native assets'
      condition: eq(variables.rid, 'windows-x64')
      inputs:
        solution: 'WebWindow.Native.sln'
        platform: 'x64'
        configuration: '$(buildConfiguration)'
    - task: CmdLine@2
      displayName: 'Create output folder for Linux'
      condition: eq(variables.rid, 'linux-x64')
      inputs:
        workingDirectory: './src/WebWindow.Native'
        script: 'mkdir x64; cd x64; mkdir $(buildConfiguration)'
    - task: CmdLine@2
      displayName: 'Build Linux native assets'
      condition: eq(variables.rid, 'linux-x64')
      inputs:
        workingDirectory: './src/WebWindow.Native'
        script: 'gcc -std=c++11 -shared -DOS_LINUX Exports.cpp WebWindow.Linux.cpp -o x64/$(buildConfiguration)/WEST.Native.so `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0` -fPIC'
    - task: CmdLine@2
      displayName: 'Create output folder for MacOS'
      condition: eq(variables.rid, 'osx-x64')
      inputs:
        workingDirectory: './src/WebWindow.Native'
        script: 'mkdir x64; cd x64; mkdir $(buildConfiguration)'
    - task: CmdLine@2
      displayName: 'Build macOS native assets'
      condition: eq(variables.rid, 'osx-x64')
      inputs:
        workingDirectory: './src/WebWindow.Native'
        script: 'gcc -shared -lstdc++ -DOS_MAC -framework Cocoa -framework WebKit WebWindow.Mac.mm Exports.cpp WebWindow.Mac.AppDelegate.mm WebWindow.Mac.UiDelegate.mm WebWindow.Mac.UrlSchemeHandler.m -o x64/$(buildConfiguration)/WEST.Native.dylib'

    #Publish native output to Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish WEST.Native.dll (windows) to artifacts'
      condition: eq(variables.rid, 'windows-x64')
      inputs:
        PathtoPublish: './src/WebWindow.Native/x64/$(buildConfiguration)/WebWindow.Native.dll'
        ArtifactName: 'WEST.Native.dll'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish WebView2Loader.dll (windows) to artifacts'
      condition: eq(variables.rid, 'windows-x64')
      inputs:
        PathtoPublish: './src/WebWindow.Native/x64/$(buildConfiguration)/WebView2Loader.dll'
        ArtifactName: 'WebView2Loader.dll'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish WEST.Native.nuspec (windows) to artifacts'
      condition: eq(variables.rid, 'windows-x64')
      inputs:
        PathtoPublish: './src/WebWindow.Native/WEST.Native.nuspec'
        ArtifactName: 'WEST.Native.nuspec'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish WEST.Native.so (linux) to artifacts'
      condition: eq(variables.rid, 'linux-x64')
      inputs:
        PathtoPublish: './src/WebWindow.Native/x64/$(buildConfiguration)/WEST.Native.so'
        ArtifactName: 'WEST.Native.so'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish WEST.Native.dylib (mac) to artifacts'
      condition: eq(variables.rid, 'osx-x64')
      inputs:
        PathtoPublish: './src/WebWindow.Native/x64/$(buildConfiguration)/WEST.Native.dylib'
        ArtifactName: 'WEST.Native.dylib'
        publishLocation: 'Container'


  #Only 1 instance - will download all native files, create NuGet package and publish to Artifacts
  - job: 'BuildPackage'
    dependsOn: 'BuildAndPublishNative'
    pool:
      vmImage: 'windows-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
    
    #Download native files from Artifacts
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'WEST.Native.dll'
        artifactName: 'WEST.Native.dll'
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'WebView2Loader.dll'
        artifactName: 'WebView2Loader.dll'
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'WEST.Native.nuspec'
        artifactName: 'WEST.Native.nuspec'
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'WEST.Native.so'
        artifactName: 'WEST.Native.so'
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'WEST.Native.dylib'
        artifactName: 'WEST.Native.dylib'
    - task: CmdLine@2
      inputs:
        script: 'ls -R'
        
    #Create NuGet package
    - task: CmdLine@2
      displayName: 'Create NuGet package'
      inputs:
        script: 'nuget.exe pack WEST.Native.nuspec -Version $(versionprefix)-$(Build.BuildNumber) -NonInteractive'

    #Publish NuGet package to Artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'WEST.Native.nupkg'
        ArtifactName: 'WEST.Native.$(versionprefix)-$(Build.BuildNumber).nupkg'
        publishLocation: 'Container'
